import type { Metadata } from "next";
import { PageIntro, Section } from "@/components/marketing/parts";
import { site } from "@/config/site";

export const metadata: Metadata = { title: "Terms" };

const blocks: [string, string][] = [
  ["The service", `${site.companyName} provides a revenue intelligence workspace: data import, pipeline and account views, briefings, conversation analysis, follow-up drafts and an action queue.`],
  ["Accounts and workspaces", "You are responsible for activity under your account and for the people you invite to your workspace. Keep credentials confidential."],
  ["Your data", "You keep ownership of the data you upload. You grant us the right to process it to provide the service to you. You confirm that you have the right to upload it."],
  ["AI output", "Briefings, answers and analysis are generated by AI from your data and can contain errors. Review them before acting. You decide what to do with them."],
  ["Credits and plans", "AI actions draw from a monthly credit allowance that depends on your plan and refreshes each billing cycle. Paid plans are purchased through a payment link run by a payment provider; your plan changes once payment is confirmed."],
  ["Acceptable use", "Do not upload unlawful content, attempt to access other workspaces, probe or disrupt the service, or use it to process data you have no right to use."],
  ["Availability and liability", "The service is provided as is, without a guarantee of uninterrupted availability or of the accuracy of AI output. To the extent permitted by law, liability is limited to the fees paid in the preceding three months."],
  ["Contact", `Questions about these terms: ${site.contactEmail}.`],
];

export default function Page() {
  return (
    <>
      <PageIntro eyebrow="Terms" title="Terms of service" />
      <Section>
        <div className="max-w-3xl space-y-8">
          {blocks.map(([t, b]) => <div key={t}><h2 className="text-xl font-semibold">{t}</h2><p className="mt-2 text-ink-soft">{b}</p></div>)}
          <p className="text-sm text-muted">Last updated: October 2026. These terms should be reviewed by counsel before launch.</p>
        </div>
      </Section>
    </>
  );
}
