"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Button, Card, Notice, Table, inputCls, td, th } from "@/components/ui";

interface Answer {
  answer: string; supporting: { label: string; value: string }[];
  table: { title: string; columns: string[]; rows: string[][] } | null; data_gaps: string | null; follow_ups: string[];
}

const suggestions = [
  "Which region is underperforming, and by how much?", "Which accounts need attention this week?", "Which reps have the strongest conversion rates?",
  "Where are deals getting stuck?", "Which opportunities have gone quiet?", "What changed since last week?", "Which sales motion produces the most wins?", "What should the team focus on next?",
];

export function Assistant({ aiReady, hasData, cost }: { aiReady: boolean; hasData: boolean; cost: number }) {
  const router = useRouter();
  const [q, setQ] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [res, setRes] = useState<(Answer & { question: string }) | null>(null);

  async function ask(question: string) {
    if (question.trim().length < 3) return;
    setBusy(true); setError(null); setRes(null);
    const r = await fetch("/api/ask", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ question }) });
    const body = await r.json().catch(() => ({}));
    setBusy(false);
    if (!r.ok) return setError(body.error ?? "Could not answer that.");
    setRes({ ...body, question }); router.refresh();
  }

  return (
    <div className="space-y-6">
      {!aiReady && <Notice tone="warn" title="AI is not configured">Set GEMINI_API_KEY and SUPABASE_SERVICE_ROLE_KEY on the server to enable questions.</Notice>}
      {!hasData && <Notice tone="neutral">Import pipeline data first — answers are built only from your own records.</Notice>}
      <form onSubmit={(e) => { e.preventDefault(); ask(q); }} className="flex flex-col gap-3 sm:flex-row">
        <input value={q} onChange={(e) => setQ(e.target.value)} maxLength={500} aria-label="Your question" placeholder="Ask the way you would say it out loud…" className={`${inputCls} h-12 flex-1 text-base`} />
        <Button type="submit" size="lg" disabled={busy || !aiReady || !hasData}>{busy ? "Reading your data…" : `Ask · ${cost} credits`}</Button>
      </form>
      <div className="flex flex-wrap gap-2">{suggestions.map((s) => <button key={s} onClick={() => { setQ(s); ask(s); }} disabled={busy || !aiReady || !hasData} className="rounded-sm border border-line-strong bg-paper px-3 py-1.5 text-left text-sm hover:border-ink disabled:opacity-50">{s}</button>)}</div>
      {error && <Notice tone="bad">{error}</Notice>}
      {res && (
        <Card>
          <div className="border-b border-ink px-5 py-4"><div className="eyebrow">Question</div><p className="display mt-1 text-2xl">{res.question}</p></div>
          <div className="space-y-5 p-5">
            <p className="text-lg leading-relaxed">{res.answer}</p>
            {res.supporting.length > 0 && <dl className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{res.supporting.map((s, i) => <div key={i} className="border-t border-ink pt-2"><dt className="text-[11px] uppercase tracking-wider text-muted">{s.label}</dt><dd className="tabular font-semibold">{s.value}</dd></div>)}</dl>}
            {res.table && res.table.rows.length > 0 && (
              <div><h3 className="mb-2 text-sm font-semibold">{res.table.title}</h3>
                <Table><thead><tr>{res.table.columns.map((c) => <th key={c} className={th}>{c}</th>)}</tr></thead><tbody>{res.table.rows.map((r, i) => <tr key={i}>{r.map((c, j) => <td key={j} className={td}>{c}</td>)}</tr>)}</tbody></Table></div>
            )}
            {res.data_gaps && <Notice tone="warn" title="Data gaps">{res.data_gaps}</Notice>}
            {res.follow_ups.length > 0 && <div className="flex flex-wrap gap-2"><span className="text-sm text-muted">Follow up:</span>{res.follow_ups.map((f) => <button key={f} onClick={() => { setQ(f); ask(f); }} className="text-sm underline">{f}</button>)}</div>}
            <p className="text-xs text-muted">Generated by AI from your workspace data. Check the figures against the Pipeline and Accounts pages before acting.</p>
          </div>
        </Card>
      )}
    </div>
  );
}
